image: public.ecr.aws/axatol/actions-job-dispatcher:latest

github:
  authSecret:
    create: true
    # name: {{ .Release.Name }}-github-credentials
    # token:
    # appId:
    # appInstallationId:
    # appPrivateKey:
    # appPrivateKeyFile:

dispatcher:
  logFormat: json # or text
  logLevel: info # or debug
  syncInterval: 5m

  config:
    create: true
    # name: {{ .Release.Name }}-config
    runners: []

  # dataVolume:
  #   ephemeral: {}

rbac:
  create: true
  # serviceAccountName: {{ .Release.Name }}

service:
  create: true
  # name: {{ .Release.Name }}
  internalPort: 8000
  externalPort: 8000

ingress:
  create: false
  annotations: {}
  hosts: []
  tls: {}
