{{- define "actions-job-dispatcher.auth-secret" -}}
{{ .Release.Name }}-auth-secret
{{- end -}}

{{- if .Values.github.authSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actions-job-dispatcher.auth-secret" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ get .Values.github.authSecret "token" | toString | b64enc }}
  GITHUB_APP_ID: {{ get .Values.github.authSecret "appId" | toString| b64enc }}
  GITHUB_APP_INSTALLATION_ID: {{ get .Values.github.authSecret "appInstallationId" | toString| b64enc }}
  GITHUB_APP_PRIVATE_KEY: {{ get .Values.github.authSecret "appPrivateKey" | b64enc }}
{{- end -}}

{{- define "actions-job-dispatcher.config" -}}
{{- if get .Values.dispatcher "configMapName" -}}
{{ .Values.dispatcher.configMapName }}
{{- else -}}
{{ .Release.Name }}-config
{{- end -}}
{{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actions-job-dispatcher.config" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    log_level: {{ .Values.dispatcher.logLevel }}
    log_format: {{ .Values.dispatcher.logFormat }}
    sync_interval: {{ .Values.dispatcher.syncInterval }}
    runners: {{ .Values.dispatcher.runners }}
