{{- if .Values.github.authSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actions-job-dispatcher.githubAuthSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.github.authSecret.token }}
  GITHUB_TOKEN: {{ .Values.github.authSecret.token | toString | b64enc }}
  {{- end }}
  {{- if .Values.github.authSecret.appId }}
  GITHUB_APP_ID: {{ .Values.github.authSecret.appId | toString| b64enc }}
  {{- end }}
  {{- if .Values.github.authSecret.appInstallationId }}
  GITHUB_APP_INSTALLATION_ID: {{ .Values.github.authSecret.appInstallationId | toString | b64enc }}
  {{- end }}
  {{- if .Values.github.authSecret.appPrivateKey }}
  GITHUB_APP_PRIVATE_KEY: {{ .Values.github.authSecret.appPrivateKey | b64enc }}
  {{- end }}
  {{- if .Values.github.authSecret.appPrivateKeyFile }}
  GITHUB_APP_PRIVATE_KEY_FILE: {{ .Values.github.authSecret.appPrivateKeyFile | b64enc }}
  {{- end }}
{{- end -}}
{{- if .Values.dispatcher.config.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actions-job-dispatcher.dispatcherConfigName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    runners: {{- .Values.dispatcher.runners | toYaml | nindent 6 }}
{{- end }}
