{{- define "actions-job-dispatcher.dispatcher" -}}
{{ .Release.Name }}
{{- end -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actions-job-dispatcher.dispatcher" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "actions-job-dispatcher.selectors" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "actions-job-dispatcher.selectors" . | nindent 8 }}
    spec:
      serviceAccountName: {{ get .Values.rbac "serviceAccountName" | default (include "actions-job-dispatcher.dispatcher" .) }}
      containers:
        - name: dispatcher
          image: {{ .Values.image }}
          serviceAccount: {{ include "actions-job-dispatcher.dispatcher" . }}
          args:
            - -config-file
            - /config/config.yaml
            - -log-format
            - {{ .Values.dispatcher.logFormat }}
            - -log-level
            - {{ .Values.dispatcher.logLevel }}
          {{- if .Values.github.authSecret.create }}
          envFrom:
            - secretRef:
                name: {{ include "actions-job-dispatcher.auth-secret" . }}
          {{- end }}
          {{- if or .Values.service.enabled .Values.ingress.enabled }}
          ports:
            - containerPort: {{ .Values.service.exposedPort }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap: {{ get .Values.dispatcher "configMapName" | print .Release.Name "-dispatcher-config" }}

        - name: data
          {{- if get .Values.dispatcher "dataVolume" }}
          {{- get .Values.dispatcher "dataVolume" | toYaml | nindent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
