---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "actions-job-dispatcher.selectors" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "actions-job-dispatcher.selectors" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "actions-job-dispatcher.serviceAccountName" . }}
      containers:
        - name: dispatcher
          image: {{ .Values.image }}
          args:
            - -config
            - /config/config.yaml
            - -namespace
            - {{ .Release.Namespace }}
          envFrom:
            - secretRef:
                name: {{ include "actions-job-dispatcher.githubAuthSecretName" . }}
          {{- if or .Values.service.create .Values.ingress.create }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- end }}
          livenessProbe:
            failureThreshold: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              path: /ping
              port: 8000
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 1
            periodSeconds: 60
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap: 
            name: {{ include "actions-job-dispatcher.dispatcherConfigName" . }}
        - name: data
          {{- if .Values.dispatcher.dataVolume }}
          {{- toYaml .Values.dispatcher.dataVolume | nindent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
