{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "actions-job-dispatcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
rules:
  - apiGroups: [batch/v1]
    resources: [jobs]
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "actions-job-dispatcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
