{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "actions-job-dispatcher.dispatcher" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "actions-job-dispatcher.dispatcher" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch/v1
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "actions-job-dispatcher.dispatcher" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "actions-job-dispatcher.dispatcher" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "actions-job-dispatcher.dispatcher" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
