{{- if or .Values.ingress.create .Values.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "actions-job-dispatcher.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "actions-job-dispatcher.labels" . | nindent 4 }}
spec:
  selector: {{- include "actions-job-dispatcher.selectors" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
{{- end -}}
