on:
  workflow_call:
    inputs:
      upload-asset:
        description: Whether or not to upload the build output
        type: boolean
        default: false
        required: false

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - run: make build

      - if: inputs.upload-asset
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ./bin
          retention-days: 1
