on:
  workflow_call:

env:
  image: public.ecr.aws/axatol/actions-runner-broker-dispatcher

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - run: actions/checkout@v3

      - run: make image

      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ./bin
          retention-days: 1

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-${{ github.event.repository.name }}-${{ github.job }}-${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.image }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}
