on:
  push:
    branches:
      - master

jobs:
  check:
    uses: ./.github/workflows/_check.yaml

  build-binary:
    needs:
      - check

    uses: ./.github/workflows/_build-binary.yaml

  build-image:
    needs:
      - check

    uses: ./.github/workflows/_build-image.yaml
    secrets:
      AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
