on:
  push:
    branches:
      - master

jobs:
  helm-lint:
    uses: ./.github/workflows/_helm-lint.yaml

  go-vet:
    uses: ./.github/workflows/_go-vet.yaml

  build-binary:
    needs:
      - helm-lint
      - go-vet

    uses: ./.github/workflows/_build-binary.yaml

  build-image:
    needs:
      - helm-lint
      - go-vet

    uses: ./.github/workflows/_build-image.yaml
    secrets:
      AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
